@startuml
'skinparam linetype ortho

together {
entity "link" as link
class "no-basis-Practitioner" as practitioner
class "no-basis-PractitionerRole" as prole

link --> practitioner
practitioner <-- prole
}

together {
class "no-basis-Person" as person
class "no-basis-Patient" as patient
class "no-basis-RelatedPerson" as relatedperson

person --[hidden] relatedperson
relatedperson --> patient
}

together {
enum "no-basis-relatedperson-person-reference" as personreference
enum "no-basis-person-citizenship" as citizenship

personreference --> citizenship
}

link -right-> relatedperson
link -right-> patient
practitioner <-left- patient
prole -> patient

patient *-right- citizenship
relatedperson *-right- personreference

@enduml