@startuml
skinparam linetype ortho

package "FHIR Entities and Individuals" #DDDDDD {
'together {
class "Patient" as patient #aliceblue ##[dotted]blue
class "Practitioner" as practitioner #aliceblue ##[dotted]blue
class "Person" as person #aliceblue ##[dotted]blue
class "PractitionerRole" as practitionerrole #aliceblue ##[dotted]blue
class "Location" as location #aliceblue ##[dotted]blue

person -down[hidden]-> practitionerrole
patient -down[hidden]-> practitioner 
}

'together {
package "no-basis Workflow" {
class "no-basis-Appointment" as appointment
class "no-basis-AppointmentResponse" as appointmentresponse
appointmentresponse -up-> appointment : appointment
}

'together {
package "FHIR Workflow" #DDDDDD {
class "Schedule" as schedule #aliceblue ##[dotted]blue
class "Slot" as slot #aliceblue ##[dotted]blue

slot -down-> schedule
}

appointment -left-> "FHIR Entities and Individuals" :participants
appointmentresponse -left-> "FHIR Entities and Individuals" 
appointment -right-> slot
@enduml