@startuml
skinparam linetype ortho

package "no-basis" {
class "no-basis-Appointment" as class1 
class "no-basis-AppointmentResponse" as class2
class2 -up-> class1 : appointment
}

package "FHIR Entities" #DDDDDD {
class "Patient" as class4
class "Practitioner" as class5

class4 -down[hidden]-> class5
class "Person" as class6
}

package "FHIR Workflow" #DDDDDD {
class "Schedule" as class7
class "Slot" as class8

class8 -down-> class7
}

'class1 -left-> class4
class1 -left-> "FHIR Entities" :participants
class2 -left-> "FHIR Entities" 
'"FHIR Entities" -right-> class1
class1 -right-> class8

'class1 -left-> "FHIR Entities" 
'class2 -left-> "FHIR Entities"
'"FHIR Entities" -left[hidden]-> "FHIR Workflow"
@enduml